---
# Sample workload for testing wozz-audit.sh
# This deployment intentionally has over-provisioned resources to test waste detection

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"  # 4x request - intentionally wasteful
            cpu: "500m"        # 5x request - intentionally wasteful
        ports:
        - containerPort: 80

---
# Another deployment without resource requests (to test missing requests detection)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-no-requests
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-no-requests
  template:
    metadata:
      labels:
        app: test-no-requests
    spec:
      containers:
      - name: app
        image: busybox:latest
        command: ["sleep", "3600"]
        # Intentionally missing resource requests/limits


